# Generated by Django 4.2 on 2023-04-20 11:25

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('bayke', '0002_baykearticlecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baykearticle',
            options={'ordering': ['-add_date'], 'verbose_name': 'BaykeArticle', 'verbose_name_plural': 'BaykeArticles'},
        ),
        migrations.AddField(
            model_name='baykearticle',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bayke.baykearticlecategory', verbose_name='文章分类'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BaykeArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='标签名')),
                ('site', models.ForeignKey(blank=True, editable=False, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'BaykeArticleTag',
                'verbose_name_plural': 'BaykeArticleTags',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='baykearticle',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bayke.baykearticletag', verbose_name='标签'),
        ),
    ]
