# Generated by Django 4.2 on 2023-04-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayke', '0006_remove_baykeuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
    ]
