# Generated by Django 4.2 on 2023-04-22 14:30

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('bayke', '0007_baykeuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeuser',
            name='email',
            field=models.EmailField(blank=True, editable=False, max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.CreateModel(
            name='BaykeVerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('code', models.CharField(blank=True, default='', max_length=4, verbose_name='验证码')),
                ('site', models.ForeignKey(blank=True, editable=False, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'VerifyCode',
                'verbose_name_plural': 'VerifyCodes',
                'ordering': ['-add_date'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
