# Generated by Django 4.2 on 2023-04-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayke', '0011_baykecart_baykecart_unique_owner_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='商品总金额'),
        ),
    ]
