# Generated by Django 4.2 on 2023-04-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayke', '0012_alter_baykeorder_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='余额'),
        ),
    ]
